{{- if .Values.adminServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.adminServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "langop-dashboard.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
{{- end }}
